name: nvitop-exporter Docker Image CI

on:
  push:
    branches: [ 'main' ]
    tags: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Git Info
        run: |
          git branch --show-current
          git status
      -
        name: Trigger Ref Name
        run: |
          export GITHUB_REF_NAME=${{ github.ref_name }}
          echo ${GITHUB_REF_NAME#v}
      -
        name: Build and Push Docker Image
        working-directory: Docker/nvitop-exporter
        run: make workflow GITHUB_REF_NAME=$GITHUB_REF_NAME
